aws:
  access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
  region: <%= ENV["AWS_REGION"] %>
concurrency: 3
delay: 10
pidfile: tmp/pids/shoryuken.pid
queues:
  - wanted_domain_check_availability
  - wanted_domain_check_availability_dev
  - dictionary_scrape
  - dictionary_scrape_dev
