---
:concurrency: 20
:pidfile: tmp/pids/sidekiq.pid
:queues:
  - drop_check_availability_dev
  - wanted_domain_check_availability
  - wanted_domain_check_availability_dev
  - dictionary_scrape
  - dictionary_scrape_dev
